### ISSUE TITLE
空格太多导致换行时，选中空格部分没有高亮

### ISSUE THREAD

**Issue by scrumbest** [ITxiaoguang/SelectTextHelper#10]
<img width="432" alt="Screenshot_20220914_154621" src="https://user-images.githubusercontent.com/3806834/190093863-43a8cd34-93cf-4b7c-b215-568cba7279a3.png">
如图所示，文字内容为1 空格 空格...  8 ，中间为n多个空格，
这种情况会导致文字换行，
然后选择空格部分，结果没有高亮

**Comment by ITxiaoguang** [comment]
是个bug，马上修复 ~~

**Comment by scrumbest** [comment]
感谢大佬，我看了下源码，这个背景是使用BackgroundColorSpan画的，然后我写了个demo，给textview设置BackgroundColorSpan，发现空格过多导致换行后就是无法给空格高亮，试了几个办法都不行。期盼大佬的结果。

**Comment by ITxiaoguang** [comment]
空格的问题，空格有挺多种的，需要我们把空格转成不间断空格  \u00A0
稍后在代码核心层加上

``` kotlin
  textView.text = textView.text.toString()
                // 半角空格(英文符号) 转 不间断空格
                .replace("\u0020", "\u00A0")
                // 全角空格(中文符号) 转 不间断空格
                .replace("\u3000", "\u00A0")
```

**Comment by ITxiaoguang** [comment]
不过这样英文单词就不能分割开了

**Comment by scrumbest** [comment]
棒棒哒，但是这个换成u00a0后，换行效果看起来和微信不一致了，微信的有对齐，我们的没对齐。还有别的办法吗？

**Comment by scrumbest** [comment]
就是说文字里那个8，微信上是第2行顶头，但更换空格后，它就不顶头了，往后面移动了几个位置。

**Comment by ITxiaoguang** [comment]
是的，我这个是直接改变了空格了，微信的没改变空格，目前不懂微信怎么实现的呢

**Comment by scrumbest** [comment]
是很难搞哦，我们试了ReplacementSpan，能画出来，但是拖动又出了问题。后来想重写TextView的draw方法，感觉也很难办。
