### ISSUE TITLE
项目无法编译

### ISSUE THREAD

**Issue by artcool** [ITxiaoguang/SelectTextHelper#12]
![image](https://github.com/ITxiaoguang/SelectTextHelper/assets/9747115/4d17cd37-6aff-4678-b341-7f456916f30f)
![image](https://github.com/ITxiaoguang/SelectTextHelper/assets/9747115/3f2d10c5-696f-4c93-a93d-ab8b7885a57f)
为什么这个插件编译不了？导致这个项目跑不起来

**Comment by ITxiaoguang** [comment]
可能是你翻不了墙吧；
https://www.pgyer.com/xW9Ccc 扫码下载就能看demo了；
通过下面这个引入项目就行了。
dependencies {
       implementation 'com.github.ITxiaoguang:SelectTextHelper:1.1.0'
}
