### ISSUE TITLE
没办法更改选项按钮

### ISSUE THREAD

**Issue by boboyuwu** [ITxiaoguang/SelectTextHelper#13]
没办法更改选项按钮

**Comment by ITxiaoguang** [comment]
可以修改的，通过下面的参数可以修改弹框选项样式
```
.addItem(0/*item的图标*/,"复制"/*item的描述*/, {Log.i("SelectTextHelper","复制")/*item的回调*/}// 操作弹窗的每个item
```

**Comment by boboyuwu** [comment]
SelectTextHelper.kt里这两行，会导致将正常输入的空格转换成全角，并且 SelectUtils.replaceContent api只替换了第一个双空格，会造成上下两段空格，上面那个被换成\u3000空格很大，下面的还保持原样不变，样式直接变了，这两段是否可去，我去掉了运行效果就正常了不知道会不会造成什么影响，可否留个联系方式详细交流请教下～

        // 处理空格 把空格转成不间断空格（\u3000）
        // 为什么处理2个，而不是1个呢？
        // 避免英文单词出现断节
        SelectUtils.replaceContent(spanStr, mOriginalContent, "\u00A0\u00A0", "\u3000\u3000")
        SelectUtils.replaceContent(spanStr, mOriginalContent, "\u0020\u0020", "\u3000\u3000")

**Comment by ITxiaoguang** [comment]
这里是为了选择文本时候空格能有底色，根据业务场景具体选择去不去掉`SelectUtils.replaceContent`的，我这里是为了fix https://github.com/ITxiaoguang/SelectTextHelper/issues/10 的问题所有加上的。

**Comment by boboyuwu** [comment]
fun replaceContent(
            stringBuilder: SpannableStringBuilder,
            mOriginalContent: CharSequence,
            targetText: String,
            replaceText: String,
        ) {
            val startIndex = mOriginalContent.toString().indexOf(targetText)
            if (-1 != startIndex) {
                val endIndex = startIndex + targetText.length
                stringBuilder.replace(startIndex, endIndex, replaceText)
            }
        }

这段代码只替换了第一个双空格，导致一段文本，上下两段两个连续空格，第一个空格被换成了"\u3000\u3000"，而后面的不变，整个文本格式变形，一摸一样的空格格式变成了这样，
复制前->:
1月23日（星期二）领导会议活动安排：
①9:00  省十四届人民代表大会第二次会议(开幕会)（平，人民会堂一楼大礼堂）
②9:30  研究办公厅信息化系统建设工作（崇松、李峰，326）


复制粘贴，控件处理后 ->
1月23日（星期二）领导会议活动安排：
①9:00    省十四届人民代表大会第二次会议(开幕会)（平，人民会堂一楼大礼堂）
②9:30  研究办公厅信息化系统建设工作（崇松、李峰，326）
