### ISSUE TITLE
大佬，我自定义的emoji表情在长按选中时没有显示背景色哦

### ISSUE THREAD

**Issue by dewi23** [ITxiaoguang/SelectTextHelper#16]
// 绑定表情 方法二：
        Map<String, Integer> emojiMap = new HashMap<>();
        emojiMap.put("[ee_0]", R.mipmap.ee_0);
        emojiMap.put("[ee_1]", R.mipmap.ee_1);
        emojiMap.put("[ee_2]", R.mipmap.ee_2);
        emojiMap.put("[ee_3]", R.mipmap.ee_3);
        emojiMap.put("[ee_4]", R.mipmap.ee_4);
        emojiMap.put("[ee_5]", R.mipmap.ee_5);
        emojiMap.put("[ee_6]", R.mipmap.ee_6);
        emojiMap.put("[ee_7]", R.mipmap.ee_7);
        emojiMap.put("[ee_8]", R.mipmap.ee_8);
        emojiMap.put("[ee_9]", R.mipmap.ee_9);
        emojiMap.put("[ee_10]", R.mipmap.ee_10);
        emojiMap.put("[ee_11]", R.mipmap.ee_11);
        emojiMap.put("[ee_12]", R.mipmap.ee_12);
        emojiMap.put("[ee_13]", R.mipmap.ee_13);

        // 使用 SelectTextHelper 的 putAllEmojiMap 方法
        SelectTextHelper.Companion.putAllEmojiMap(emojiMap);

        mSelectableTextHelper = new SelectTextHelper.Builder(mTvDetailContent) // 放你的 textView 到这里
                .setCursorHandleColor(ContextCompat.getColor(mActivity, R.color.colorAccent)) // 游标颜色
                .setCursorHandleSizeInDp(22f) // 游标大小 单位 dp
                .setSelectedColor(ContextCompat.getColor(mActivity, R.color.color_D9E4FF)) // 选中文本的颜色
                .setSelectAll(false) // 初次选中是否全选，默认为 true
                .setScrollShow(true) // 滚动时是否继续显示，默认为 true
                .setSelectedAllNoPop(false) // 已经全选无弹窗，设置了监听会回调 onSelectAllShowCustomPop 方法
                .setMagnifierShow(false) // 放大镜，默认为 true
                .setSelectTextLength(2) // 首次选中文本的长度，默认为 2
                .setPopDelay(100) // 弹窗延迟时间，默认为 100 毫秒
                //.setPopAnimationStyle(R.style.Base_Animation_AppCompat_Dialog) // 弹窗动画，默认为无动画
                .addItem(0, getString(R.string.copys), new SelectTextHelper.Builder.onSeparateItemClickListener() {
                    @Override
                    public void onClick() {
                        copy();
                    }
                }) // 操作弹窗的每个 item
                .setPopSpanCount(5) // 设置操作弹窗每行个数，默认为 5
                .setPopStyle(R.drawable.shape_color_4c4c4c_radius_8, 0) // 设置操作弹窗背景色、箭头图片
                .build();
![20241119-162340](https://github.com/user-attachments/assets/bfdbd0ab-d27a-449b-82e4-7ac4958edf28)

**Comment by ITxiaoguang** [comment]
emoji表情需要继承 `https://github.com/ITxiaoguang/SelectTextHelper/blob/master/selecttext/src/main/java/com/xiaoguang/selecttext/SelectImageSpan.kt`才可以，或者把资源文件放到drawable里面试试

**Comment by dewi23** [comment]
试了还是不行。也继承了SelectImageSpan

**Comment by ITxiaoguang** [comment]
把完整的demo下下来，试试呢，里面有具体实现，demo里用的是`com/xiaoguang/selecttextview/MsgAdapter.kt`富文本,改成普通文本试试。

```kotlin
// todo 方法二：普通文本
holder.textView.text = msgBean.content
// 演示消息列表选择文本
holder.selectText(msgBean)
```

**Comment by dewi23** [comment]
// 假设保存了旧的选中范围
    private var oldStart = -1
    private var oldEnd = -1

    private fun onSelectionChanged(newStart: Int, newEnd: Int) {
        if (oldStart == -1 || oldEnd == -1) {
            // 如果是第一次拖动，初始化旧范围
            oldStart = newStart
            oldEnd = newEnd
        }

        // 调用方法 3，更新表情背景色
        setEmojiBackground(oldStart, oldEnd, newStart, newEnd)

        // 更新旧范围
        oldStart = newStart
        oldEnd = newEnd
    }

    private val allImageSpan: MutableList<SelectImageSpan> = ArrayList<SelectImageSpan>()

    private fun setEmojiBackground(oldStart: Int, oldEnd: Int, newStart: Int, newEnd: Int) {
        if (mSpannable == null) {
            return
        }

        // 清除旧选中范围的背景色
        if (oldStart < oldEnd) { // 确保范围合法
            val oldSpans = mSpannable!!.getSpans(
                oldStart, oldEnd,
                ImageSpan::class.java
            )
            for (span in oldSpans) {
                val spanStart = mSpannable!!.getSpanStart(span)
                val spanEnd = mSpannable!!.getSpanEnd(span)

                // 移除旧的背景高亮
                val existingSpans: Array<SelectImageSpan> =
                    mSpannable!!.getSpans<SelectImageSpan>(
                        spanStart, spanEnd,
                        SelectImageSpan::class.java
                    )
                for (selectSpan in existingSpans) {
                    mSpannable!!.removeSpan(selectSpan)
                }
            }
        }

        // 设置新选中范围的背景色
        if (newStart < newEnd) { // 确保范围合法
            val newSpans = mSpannable!!.getSpans(
                newStart, newEnd,
                ImageSpan::class.java
            )
            for (span in newSpans) {
                val spanStart = mSpannable!!.getSpanStart(span)
                val spanEnd = mSpannable!!.getSpanEnd(span)
                val emojiDrawable = span.drawable

                // 设置新的高亮
                val highlightSpan =
                    SelectImageSpan(
                        emojiDrawable,
                        mSelectedColor,
                        DynamicDrawableSpan.ALIGN_BOTTOM
                    )
                mSpannable!!.setSpan(
                    highlightSpan,
                    spanStart,
                    spanEnd,
                    Spannable.SPAN_EXCLUSIVE_EXCLUSIVE
                )
                allImageSpan.add(highlightSpan)
            }
        }
    }
我用自己的方法实现了， // 设置图片表情选中背景
//设置emoji背景色
 selectText()方法里面调用onSelectionChanged(mSelectionInfo.mStart, mSelectionInfo.mEnd)
