### ISSUE TITLE
对于设置过imageSpan拼接TextView的字符表情，无法设置选择态（即设置 BackgroundColorSpan无效），暂无法解决。

### ISSUE THREAD

**Issue by ITxiaoguang** [ITxiaoguang/SelectTextHelper#4]
望广大老铁给予帮助。

**Comment by ITxiaoguang** [comment]
https://github.com/laobie/SelectableTextHelper/issues/4

**Comment by gnmmdk** [comment]
class VvImageSpan(drawable:Drawable , @ColorInt val bgColor:Int, verticalAlignment:Int ) : ImageSpan(drawable, verticalAlignment) {
    override fun draw(
        canvas: Canvas,
        text: CharSequence?,
        start: Int,
        end: Int,
        x: Float,
        top: Int,
        y: Int,
        bottom: Int,
        paint: Paint
    ) {
        val b = drawable
        canvas.save()
        paint.color = bgColor
        canvas.drawRect(x, top.toFloat(),x+b.bounds.right, bottom.toFloat(),paint)
        var transY = (bottom - top - b.bounds.bottom) / 2 + top
        canvas.translate(x, transY.toFloat())
        b.draw(canvas)
        canvas.restore()
    }

}
通过这种方式设置背景
