### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by Nuyoah965** [ITxiaoguang/SelectTextHelper#5]
添加2个文本的item类型，数据均超过一屏幕，长按文本类型，会显示全选，然后下滑动RV使文本下面的光标超出底部，然后上滑使上面的光标超出上屏，然后往上滑，再次长按文本，弹出pop，上面的pop会先闪一下，再消失，具体查看以下视频。

https://user-images.githubusercontent.com/27824757/165697081-cdbbbf5b-dc3f-4209-b41d-0fd95561de16.mp4

**Comment by chengzhuangjie** [comment]
使用java，没有
SelectTextHelper.putAllEmojiMap(emojiMap)方法

**Comment by licoba** [comment]
+1，同样报错
![image](https://github.com/ITxiaoguang/SelectTextHelper/assets/19327381/8879997a-dbf9-42d1-b9c6-03e98cb31d58)

**Comment by ITxiaoguang** [comment]
> 使用java，没有 SelectTextHelper.putAllEmojiMap(emojiMap)方法

没留意到这个issue，新版已经发出来了，可以用了。

**Comment by ITxiaoguang** [comment]
> +1，同样报错 ![image](https://user-images.githubusercontent.com/19327381/238227921-8879997a-dbf9-42d1-b9c6-03e98cb31d58.png)

新版可以用了，前面没发版。
