### ISSUE TITLE
建议增加选中的文本的起始位置pos_start

### ISSUE THREAD

**Issue by 9292922** [ITxiaoguang/SelectTextHelper#6]
如题，在做阅读文章划线功能的时候，需要获取选中文本的起始位置，才能实现划线功能逻辑。
当然，也有可以根据选中的文本用indexOf获取，但是当选择文本太短等等情况，就会导致误查找

**Comment by ITxiaoguang** [comment]
是的目前没这个属性。
设置默认选中文本个数，看能不能符合你的需求。
```java
SelectTextHelper mSelectableTextHelper=new SelectTextHelper
    .Builder(textView)
    .setSelectAll(false)// 初次选中是否全选 default true
    .setSelectTextLength(8)// 首次选中文本的字符长度8，需要设置setSelectAll(false) default 2
    .addItem(0/*item的图标*/,"复制"/*item的描述*/,
    ()->Log.i("SelectTextHelper","复制")/*item的回调*/)// 操作弹窗的每个item
    .build();
```

**Comment by 9292922** [comment]
> 是的目前没这个属性。 设置默认选中文本个数，看能不能符合你的需求。
> 
> ```java
> SelectTextHelper mSelectableTextHelper=new SelectTextHelper
>     .Builder(textView)
>     .setSelectAll(false)// 初次选中是否全选 default true
>     .setSelectTextLength(8)// 首次选中文本的字符长度8，需要设置setSelectAll(false) default 2
>     .addItem(0/*item的图标*/,"复制"/*item的描述*/,
>     ()->Log.i("SelectTextHelper","复制")/*item的回调*/)// 操作弹窗的每个item
>     .build();
> ```
![image](https://user-images.githubusercontent.com/25112746/183362643-dcbf69fa-aa25-4afa-8685-55c2a650d9d6.png)


目前通过修改interface就可以实现了哦

**Comment by 9292922** [comment]
> 是的目前没这个属性。 设置默认选中文本个数，看能不能符合你的需求。
> 
> ```java
> SelectTextHelper mSelectableTextHelper=new SelectTextHelper
>     .Builder(textView)
>     .setSelectAll(false)// 初次选中是否全选 default true
>     .setSelectTextLength(8)// 首次选中文本的字符长度8，需要设置setSelectAll(false) default 2
>     .addItem(0/*item的图标*/,"复制"/*item的描述*/,
>     ()->Log.i("SelectTextHelper","复制")/*item的回调*/)// 操作弹窗的每个item
>     .build();
> ```

谢谢您的回复

**Comment by ITxiaoguang** [comment]
建议用最新的代码哦，最新的还支持图片自由复制，demo有案例。
