### ISSUE TITLE
文本选择遇到/n换行的时候，选择会有问题

### ISSUE THREAD

**Issue by 9292922** [ITxiaoguang/SelectTextHelper#7]
如题，当我想选中如图所示的一句话时，当它是一段的结尾并且有换行时，就会强制把/n选中，这个倒是也可以自己做处理，但是selectTextHelper的游标hander显示会出错，体验不是特别好!

理应handle在一句话的结尾而不是换行之后。如下两张图

[Screenshot_2022-08-07-17-00-57-930_com.magicalstory.reader.jpg](https://user-images.githubusercontent.com/25112746/183283568-883661c5-f8aa-401a-bf93-37a59909865f.jpg)

![Screenshot_2022-08-07-17-05-30-318_com.magicalstory.reader.jpg](https://user-images.githubusercontent.com/25112746/183283592-fdd0af17-c3bb-4bba-8ba1-cbd492b0c649.jpg)

**Comment by ITxiaoguang** [comment]
已经修改好了，就是没发版，可以拉取新的代码来替换哈，https://github.com/ITxiaoguang/SelectTextHelper/issues/3

**Comment by 9292922** [comment]
> 已经修改好了，就是没发版，可以拉取新的代码来替换哈，#3

谢谢，根据您提供的代码已经修复

**Comment by 9292922** [comment]
> 已经修改好了，就是没发版，可以拉取新的代码来替换哈，#3

我用的是java的，hhh，还没学kotlin
