### ISSUE TITLE
和ClickableSpan点击冲突咋解决

### ISSUE THREAD

**Issue by xwzwayne** [ITxiaoguang/SelectTextHelper#9]

**Comment by xwzwayne** [comment]
我们im里有些自定义消息是部分文字加颜色可以点击，然后跳转自己的业务逻辑的。现在这个库的点击和ClickableSpan里的点击冲突，ClickableSpan不能点击了

**Comment by ITxiaoguang** [comment]
是的，已经被框架改写了，目前只支持链接的点击，通过listener.onClickUrl(String url)回调。
注释` mTextView.movementMethod = LinkMovementMethodInterceptor()`这句就能用你代码里的方法。
当然如果你想要更丰富的使用，需要自行修改SelectTextHelper里的LinkMovementMethodInterceptor内部类即

**Comment by xwzwayne** [comment]
谢谢，改了LinkMovementMethodInterceptor里的逻辑可以了
